### PR TITLE
[Feature] Added github stars on the page #9

### PR DESCRIPTION
**Pull request by kushcoder12**
I have added the Git-Hub Star, By updating index.html, please have a look @eduardconstantin :)

### CODE REVIEW

**Comment by kushcoder12** [comment]
Screenshot from 2022-10-11 12-42-19
have a look.

**Comment by eduardconstantin** [comment]
Sorry but this is not the right way to do it.

**Comment by kushcoder12** [comment]
how would you like me to do it? kindly elaborate

**Comment by eduardconstantin** [comment]
@kushcoder12 you can find an example [here](https://github.com/eduardconstantin/Crypto-Rankings)

**Comment by kushcoder12** [comment]
> @kushcoder12 you can find an example [here](https://github.com/eduardconstantin/Crypto-Rankings)

on which page you want the star?

**Comment by eduardconstantin** [comment]
Should be in App.js

**Comment by kushcoder12** [comment]
OK got it working on it. :)

**Comment by eduardconstantin** [comment]
@kushcoder12 are you still working on this?

**Pull request closed without merging**
