### PR TITLE
[Feature] Create npm package 

### LINKED ISSUE #16: [Feature] Create npm package
I would like to create an NPM package for this button to be easier to use.

### PR DESCRIPTION
**Pull request by aaheli8**
Created an NPM package for the react component.
## Description

Created the npm package using storybook and Rollup.

Closes #16 

## How Has This Been Tested?

This has been tested in localhost as well as by publishing the npm package on the npm website for test purposes.

Installed the package comic-book-button-1 on a demo project and ran it on localhost.
image

The package has been published on npm for only testing.
image

# Testing in a demo project
``` javascript
import React from 'react';
import {ComicButton} from 'comic-book-button-1';
export default function Button() {
  return (
    <div><ComicButton buttonName='BUTTON' focusBtnName='hello' hoverBtnName='HOVER' />
    </div>
  )
}
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes. They do not dramatically decrease the test coverage metric
- [ ] All new and existing tests passed.
- [x] I give my permission for my code to be used in this project under this license and any future license terms

### CODE REVIEW

**Comment by eduardconstantin** [comment]
Don’t add the node modules folder

**Comment by aaheli8** [comment]
@eduardconstantin Okay making the necessary changes

**Comment by aaheli8** [comment]
I removed the node_modules folder

**Comment by eduardconstantin** [comment]
Great! Thank you! Don't forget to star the repo.

**Review by eduardconstantin — APPROVED** [review]

**Comment by eduardconstantin** [comment]
@all-contributors please add @aaheli8 for code

**Pull request merged**
