### PR TITLE
did some design improvements

### PR DESCRIPTION
**Pull request by VedantKCSE**
hope you would like these changes in ReadMe.md

### CODE REVIEW

**Review by eduardconstantin — COMMENTED** [review]
Could you move **Props** above **Steps to follow**?

**Comment by VedantKCSE** [comment]
> Could you move **Props** above **Steps to follow**?

Ya sure 👍

**Comment by VedantKCSE** [comment]
> Could you move **Props** above **Steps to follow**?

Done 👍🤟

**Comment by eduardconstantin** [comment]
Great! Thank you!

**Pull request merged**
